name: furshed
description: Flutter project working with API ruz.fa.ru.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^8.2.0

  cupertino_icons: ^1.0.2
  dio: ^5.7.0
  intl: ^0.19.0
  # loadmore_listview: ^1.0.7
  # provider: ^6.1.2
  time_scheduler_table:
    path: ../time_scheduler_table/
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/